### ISSUE TITLE
No issue, but i dnt have where to send you a question

### ISSUE THREAD

**Issue by Nacurutu** [vladmandic/sd-extensions#1]
Hey @vladmandic , just to ask, the webUI Info tab is no longer on the repo :(

May I ask, did you remove it? and why? it is so good the information that the tab brings to the user of the webUI.

Best regards,

**Comment by vladmandic** [comment]
I'm reorganizing my repos, it's going to be rehosted, not gone forever...

**Comment by Nacurutu** [comment]
@vladmandic 
Oh.. ok.. Perfect... Thanks a lot

Also, I got inspired by your CSS and made some improvements to my user.css file...

But your code is 100 times better than mine. xD

Just in case you want to give it a look: https://github.com/Nacurutu/Dark-Themes-SD-WebUI-Automatic1111

I have mentioned u in the comment  :p 

PS: Waiting for the Info tab again.
PS2: sorry to post on issues

**Comment by vladmandic** [comment]
@Nacurutu took a look at your page, looks cool - and thanks for the shoutout...

btw, i'm about to shutdown this repo as i've created a separate repo for each extension and merged the rest into my main fork:
<https://github.com/vladmandic/automatic>

**Comment by Nacurutu** [comment]
> @Nacurutu took a look at your page, looks cool - and thanks for the shoutout...

Thank you, and not a problem for the shoutout...
> 
> btw, i'm about to shutdown this repo as i've created a separate repo for each extension and merged the rest into my main fork: https://github.com/vladmandic/automatic

Ok, I'm gonna follow that repo, and follow the new one.. :)

Great job by the way, already installed the new info tab, the new aestethiv scorer,.. and going to check what can I use from the new repo :p... 

for example, gonna see how to do this on mine:

If you're using PyTorch 2.0 models will be auto-compiled and optimized on load
Using max-tune
Updated Python libraries to latest known compatible versions
e.g. accelerate, transformers, numpy, etc.

**Comment by vladmandic** [comment]
`torch.compile` "works", but doesn't do much just yet - need to dig deeper into that.
